[package]
name = "ctes-models"
description = "Ciphertext Ecosystem models for Rust."
license = "MIT"
version = "0.1.1"
edition = "2024"

[dependencies]
prost = "0.14.3"
prost-types = "0.14.3"
tonic-build = "0.14.2"

[build-dependencies]
prost-build = "0.14.3"
protoc-bin-vendored = "3.2.0"